name: CICD using Maven and Jenkins
on:
  push:
  workflow_dispatch:

jobs:
  CICDJob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo on ubuntu server
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build the source code
        run: mvn package
        run: mvn pmd:pmd 
