name: CICD using Maven and Jenkins
on:
  push:
  workflow_dispatch:
jobs:
  CICDJob:
    runs-on: ubuntu-latest
    steps:
    - name: clone the repo on ubuntu server
      uses: action/checkout@v5.0.0
    - name: install java on ubuntu and maven
      uses: actions/setup-java@v5.0.0
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Build the source code 
      run: mvn package
